config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'baats#index'

  resources :baats,         only: [:index, :create]
  resources :templates,     only: [:index, :create]
  resources :volumes,       only: [:index, :create]
  resources :images,        only: [:index, :create]

  get   '/pdfs', to: 'pdf_originals#index', as: 'pdf_originals'
  post  '/pdfs', to: 'pdf_originals#create'

end

app/models/pdf_original.rb
require 'fileutils'

class PdfOriginal < ActiveRecord::Base

  #-------------------------------------------------
  #    Associations
  #-------------------------------------------------
  belongs_to :collection

  #-------------------------------------------------
  #    Validations
  #-------------------------------------------------

  #-------------------------------------------------
  #    Scopes
  #-------------------------------------------------

  #-------------------------------------------------
  #    States
  #-------------------------------------------------

  #-------------------------------------------------
  #    Public Methods
  #-------------------------------------------------
  # def self.save_files(pdfs, wiki, collection)
  #   directory = 'public/uploads/pdfs'
  #   pdfs.each do |pdf|
  #     path = extract_path(pdf)
  #     root, *categories, filename = path.split('/')
  #     raise IOError, "Wrong directory selected. Please select 'PDFs' instead of '#{root}'." unless root.match(/\APDFs\z/)
  #     filepath = File.join(directory, collection.name, categories)
  #     create_category_folders(filepath)
  #     filepath = File.join(filepath, filename)
  #     File.open(filepath, 'wb') { |file| file.write(pdf.read) }
  #     puts "File uploaded: #{filename}"
  #   end
  #   true
  # rescue IOError => input_error
  #   input_error
  # end

  # def self.save_files(pdfs, wiki, collection)
  #   pdfs.each do |pdf|
  #     path = extract_path(pdf)
  #     root, *categories, filename = path.split('/')
  #     raise IOError, "Wrong directory selected. Please select 'PDFs' instead of '#{root}'." unless root.match(/\APDFs\z/)
  #     # pdf_original = PdfOriginal.new
  #     # pdf_original.pdf_file = pdf
  #     # pdf_original.save!
  #     # pdf_original = PdfOriginal.create!(name: filename)

  #     path      = pdf.path
  #     # filename  = pdf.original_filename
  #     AWSUploader.perform_async(path)

  #     # puts "File uploaded: #{pdf_original.pdf_file.url}"
  #   end
  #   true
  # rescue IOError => input_error
  #   input_error
  # end

#=================================================
  private
#=================================================

    def self.extract_path(file)
      file.headers.match(/(filename=)("(.+)")/).captures.last
    end

    def self.create_category_folders(filepath)
      FileUtils.mkpath(filepath) unless File.exists? filepath
    end

end

app/views/pdf_originals/_pdf_original.haml
%li= pdf_original.name
%li= pdf_original.pdf_file

app/views/pdf_originals/create.js.erb
<% if @pdf.new_record? %>
  alert("Failed to upload PDF: <%= j @pdf.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#pdfs").append("<%= j render(@pdf) %>");
<% end %>

app/views/pdf_originals/index.haml
.row
  .col-md-12
    = link_to 'uploads', baats_path

.row
  .col-md-12
    %h3.text-center PDF Upload Status
    %hr

.row
  .col-md-5
    %h4.text-center Messages
    = render 'shared/flash'
    .upload-alerts

  .col-md-7
    %h4.text-center Pages
    .upload-progress


/ %h3 All PDFs

/ %br

/ = form_for PdfOriginal.new, html: { :class => 'directupload', multipart: true, data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host }} do |f|
/   = f.label :pdf_file, "Upload PDFs:"
/   = f.file_field :pdf_file, name: "pdf_file", multiple: true
/   = f.submit 'Save', :class => 'btn'

/ %hr

/ %h4 PDF Gallery
/ #pdf_originals
/   = render @pdf_originals

/ .clear

/ %script#pdf-upload{:type => "text/x-tmpl"}
/   .upload
/     {%=o.name%}
/     .progress
/       .bar{:style => "width: 0%;"}